name = "e-store-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
VITE_API_URL = "https://jogjabootcamp-api.wahwooh.workers.dev"
VITE_QUIZ_URL = "https://awal.jogjabootcamp.com"
VITE_GA_TRACKING_ID = "G-6FQYM0MBV2"
